config/routes.rb
Rails.application.routes.draw do
  resources :news
  resources :comments
  resources :topics do
      resources :comments
  	collection do
  		get :listOf
  		get :blocklistOf
  	end
  end
  devise_for :users
  resources :users, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#index'
end

app/models/topic.rb
class Topic < ApplicationRecord
	belongs_to :user
	has_many :comments

  validates :name, length: { minimum: 3 , message: "Co najmniej 3 znaki."}

  validates :desc, length: { minimum: 5 , message: "Co najmniej 5 znaków."}
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  load_and_authorize_resource
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column,:sort_direction

  expose :topic
  # GET /topics
  # GET /topics.json
  def index
    if params[:sort] == "created_at"
            @topics = Topic.order(sort_column + ' ' + sort_direction).page(params[:page]).per(8)

    else
        @topics = Topic.page(params[:page]).per(8).left_joins(:comments)
        .group(:id)
        .order('COUNT(comments.id) DESC')
    end

  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @topics = Topic.find(params[:id])
    @comments = @topics.comments.page(params[:page]).per(10).order(created_at: :desc)
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)
    @topic.user = current_user
      if @topic.save
        redirect_to @topic, notice: 'Topic was successfully created.'
      else
        render :new 
      end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update

      if @topic.update(topic_params)
        redirect_to @topic, notice: 'Topic was successfully updated.'
      else
        render :edit
      end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy

    redirect_to topics_url, notice: 'Topic was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:name, :desc, :published)
    end
  def sort_column
    Topic.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_commentList.html.erb
 <p> dasadasdasd</p>
 <main role="main" class="container">
  <div class="jumbotron">
  	<% if comments.empty? %>
  		<p class="lead">Brak komentarzy</p>
  	<% else %>
  		<% comments.each do |comment| %>
		    <h1><%= comment.user.username %></h1>
		    <p><%= @topic.desc %></p>
		    <a><%= link_to 'Edit', edit_comment_path(comment), class: "btn btn-lg btn-primary"  %></a>

		<% end %>
    <% end %>
  </div>
</main>

app/views/topics/_form.html.erb
<%= form_with(model: topic, local: true) do |form| %>
  <% if topic.errors.any? %>
    <div class="alert alert-danger">
      <h2>Wystąpiły <%= topic.errors.count %> błędy.</h2>

      <ul>
      <% topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label>Nazwa</label>
    <p>
    <%= form.text_field :name %>
  </p>
  </div>

  <div class="field">
    <label>Opis    </label>
    <p>
    <%= form.text_area :desc %>
  </p>
  </div>

  <div class="field">
    <%= form.label :published %>
    <%= form.check_box :published %>
  </div>

  <div class="actions">
    <%= form.submit "Akceptuj" ,class: "btn btn-primary btn-lg "%>
    <%= link_to 'Wróć', topic, class: "btn btn-success btn-lg"%>
  </div>
<% end %>

app/views/topics/_indexList.html.erb
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th class="col-md-4">Name</th>
        <th class="col-md-4">Desc</th>
        <th class="col-md-2">Author</th>
        <th class="col-md-2">Published</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @topics.each do |topic| %>
        <tr>
          <td class="col-md-4"><%= topic.name %></td>
          <td class="col-md-4"><%= topic.desc %></td>
          <td class="col-md-2"><%= topic.user.try(:username) %></td>
          <td class="col-md-2"><%= topic.published %></td>
          <td><%= link_to 'Show', topic, class: "btn btn-primary" %></td>
          <td>
            <% if can? :update, topic %>
                <%= link_to 'Edit', edit_topic_path(topic), class: "btn btn-warning" %>
            <% end %>
          </td>
          <td>
            <% if can? :destroy, topic %>
              <%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning" %>
              <% end %>
            </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>

app/views/topics/_topics.html.erb
<% @topics.each_slice(4) do |slice| %>
  <div class="row">
    <% slice.each do |topic| %>
      <div class="col-md-3">
        <div class="thumbnail">
          <div class="caption">
            <h3><%= topic.name %></h3>
            <p><%= simple_format(truncate(topic.desc, length: 90)) %></p>
            <p><%= topic.user.username %></p>
            <p> <%= link_to 'Show', topic, class: "btn btn-primary" %></p>
          </div>
          </div>
        </div>
    <% end %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Edytuj temat</h1>

<%= render 'form', topic: @topic %>

app/views/topics/index.html.erb
<%= flash_messages %>

<% if can? :create, topic %>
<h2>Topics</h2><%= link_to 'New Topic', new_topic_path , class: "btn btn-primary" %>
<% end %>
<p />
<p> 
    <%= sortable "created_at"%>
    <%= link_to 'Najpopularniejsze', topics_path, class: "btn btn-primary" %></p>
<p></p>
<% @topics.each_slice(4) do |slice| %>
  <div class="row">
    <% slice.each do |topic| %>
      <div class="col-md-3 text-center">
        <div class="thumbnail">
          <div class="caption">
            <h3><%= topic.name %></h3>
            <p><%= simple_format(truncate(topic.desc, length: 90)) %></p>
            <p><%= topic.user.username %></p>
            <p><%= topic.comments.count %> </p>
            <p> <%= link_to 'Wyświetl', topic, class: "btn btn-primary" %></p>
          </div>
          </div>
        </div>
    <% end %>
  </div>
<% end %>
<hr />
<%= paginate @topics %>
<%= page_entries_info @topics %>
<br>

app/views/topics/new.html.erb
<h1>Dodaj temat</h1>

<%= render 'form', topic: @topic %>

app/views/topics/show.html.erb
<%= flash_messages %>


 <main role="main" class="container">
  <div class="jumbotron">
    <h1><%= @topic.name %></h1>
    <p class="lead"><%= @topic.desc %></p>
    <% if can? :update, topic %>
    <%= link_to 'Edycja', edit_topic_path(@topic), class: "btn btn-lg btn-primary"  %>
	<%= link_to 'Usuń', topic_path(@topic), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-lg btn-danger" %>

    <% end %>
    <%= link_to 'Wróć', topics_path, class: "btn btn-lg btn-primary"  %>
  </div>
</main>

<main role="main" class="container">
	<div class="jumbotron " style="background:grey !important">
		<h2>Dodaj komentarz</h2>
		<% if !user_signed_in? %>
		<p class="lead">Nie możesz dodawać komentarzy</p>
		<% else %>
		<%= form_for([@topic, @topic.comments.build])  do |f| %>

			   <div class="form-group col-md-10 ">
			    <%= f.text_area :desc, class: "form-control" %>
				</div>
			
			  <div class="actions">
    				<%= f.submit "Dodaj",  class: "btn btn-lg btn-success" %>
  				</div>
			<% end %>
		<% end %>
  	</div>
</main>

<main role="main" class="container">
	<div class="jumbotron " style="background:white !important">
		<% if @comments.empty? %>
			<p class="lead">Brak komentarzy</p>
		<% else %>
			<% @comments.each do |comment| %>
			<hr />
				<h2><%= comment.user.username %></h2>
				<p><%= comment.desc %></p>
				<% if can? :manage, comment %>
				<%= link_to 'Edcyja', edit_comment_path(comment), class: "btn btn-lg btn-primary"  %>
				<%= link_to 'Usuń', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-lg btn-danger" %>
				<% end %>
			<% end %>
		<% end %>
	</div>
</main>
<%= paginate @comments %>
<%= page_entries_info @comments %>