config/routes.rb
Rails.application.routes.draw do
  resources :news
  resources :comments
  resources :topics do
      resources :comments
  	collection do
  		get :listOf
  		get :blocklistOf
  	end
  end
  devise_for :users
  resources :users, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#index'
end

app/models/news.rb
class News < ApplicationRecord
	belongs_to :user
	has_one_attached :image
	
  	validates :name, length: { minimum: 5 , message: "Co najmniej 5 znaki."}

  	validates :desc, length: { minimum: 10 , message: "Co najmniej 10 znaków."}
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]


  # GET /news
  # GET /news.json
  def index
    @news = News.order(created_at: :desc).page(params[:page]).per(10)
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create

    @news = News.new(news_params)
    @news.user = current_user

      if @news.save
        redirect_to @news, notice: 'News was successfully created.'
      else
        render :new 
      end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
      if @news.update(news_params)
        redirect_to @news, notice: 'News was successfully updated.'
      else
        render :edit
      end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
      redirect_to news_index_url, notice: 'News was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:name, :desc, :image)
    end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<%= form_with(model: news, local: true) do |form| %>
  <% if news.errors.any? %>
   <div class="alert alert-danger">
      <h2>Wystąpiły <%= news.errors.count %> błędy.</h2>
      <ul>
      <% news.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    
      <label>Nazwa</label>
    <p>
    <%= form.text_field :name %>
  </p>
  </div>

  <div class="field">
    
      <label>Treść</label>
    <p>
    <%= form.text_area :desc %>
  </p>
  </div>
  <div class="field">
    <label><%= form.label :image, :class => "control-label col-md-1" %></label>
    <p>
     <%= form.file_field :image %></td>
   </p>
  </div>
  <div class="actions">
    <%= form.submit "Akceptuj", class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/news/edit.html.erb
<h1>Edycja Newsa</h1>

<%= render 'form', news: @news %>

<%= link_to 'Show', @news, class: "btn btn-lg btn-primary" %> |
<%= link_to 'Back', news_index_path, class: "btn btn-lg btn-success" %>

app/views/news/index.html.erb
<%= flash_messages %>
<p ></p>
<% if can? :create, News %>
<%= link_to 'Dodaj nowy news', new_news_path , class: "btn btn-lg btn-primary"%>
<% end %>
    <% if @news.empty? %>
      <p class="lead">Brak news</p>
    <% else %>
      <% @news.each do |news| %>
      <main role="main" class="container">
      <div class="jumbotron ">
      <hr />
      <div class="row">
        <div class="col-md-2">
               <% if news.image.attached? %>
                    <%= image_tag news.image.variant(resize: "100x100") %>
              <% end %>
        </div>
        <div class="col-md-10">
           <h2><%= news.name %></h2>

              <p><%= simple_format(truncate(news.desc, length: 90)) %></p>
              <%= link_to 'Wyświetl', news, class: "btn btn-lg btn-primary"  %>
              <% if can? :manage, news %>
              <%= link_to 'Edcyja', edit_news_path(news), class: "btn btn-lg btn-primary"  %>
              <%= link_to 'Usuń', news_path(news), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-lg btn-danger" %>
              

              <% end %>
        </div>
             
      </div>
         <hr />
          </div>
      </main>
      <% end %>
    <% end %>


<%= paginate @news %>
<%= page_entries_info @news %>

app/views/news/new.html.erb
<h1>Dodaj nowy</h1>

<%= render 'form', news: @news %>

<%= link_to 'Back', news_index_path , class: "btn btn-lg btn-success"%>

app/views/news/show.html.erb
<%= flash_messages %>
<main role="main" class="container">
	<div class="jumbotron ">
		<hr />
		<div class="row">
	        <div class="col-md-2">
	        	<% if @news.image.attached? %>

	      			<%= image_tag @news.image.variant(resize: "100x100") %>
				<% end %>
	        </div>
	        <div class="col-md-10">
	        	<h2><%= @news.name %></h2>
				<p><%= @news.desc %></p>
				<%= link_to 'Wróć', news_index_path, class: "btn btn-lg btn-success"  %>
				<% if can? :manage, @news %>
				<%= link_to 'Edcyja', edit_news_path(@news), class: "btn btn-lg btn-primary"  %>
				<%= link_to 'Usuń', news_path(@news), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-lg btn-danger" %>
				

				<% end %>
	        </div>
       	</div>
		<hr />
  	</div>
</main>